server:
  port: 9527


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  #新的访问路径变为: http://localhost:9527/mydept/dept/get/1
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  #忽略掉原路径访问 http://localhost:9527/microservicecloud-dept/dept/get/1
  #这个路径访问不成功
  ignored-services: microservicecloud-dept
  #为所有的路路径前面加一个前缀  http://localhost:9527/atitcast/mydept/dept/get/1
  prefix: /atitcast

  # * 代表忽略掉所有的服务
  #ignored-services: *


spring:
  profiles:
    active: dev
---
spring:
  profiles: dev         #开发环境
  application:
    name: microservicecloud-config-dev

---
spring:
  profiles: test        #测试环境
  application:
    name: microservicecloud-config-test

#请保存为UTF-8格式