server:
  port: 80


feign:
  hystrix:
    enabled: true

eureka:
  client:
    #自身不注册进eureka当中,但是需要从eureka当中获取服务的提供方
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

